name: CI
on: [push, pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Typecheck
        run: pnpm typecheck

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Run tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          FORCE_COLOR: 1
        run: pnpm test -r
